### ISSUE TITLE
Améliorer le calendrier

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#105]
### Comportement actuel
les chiffres sont gris foncés ou noirs et non cliquables si antérieurs

commentaire d'Alex 
Un clic sans reaction est tjrs desagreable ds notre inconscient. Mieux vzut qu un code couleur nous incite à cliquer ailleurs

### Comportement attendu
Sur covoiturage-libre lorsque je recherche un trajet il serait bien de colorier en gris les dates antérieures. Exemple en capture écran. Mettre en gris les jours antérieurs et en une autre couleurs les jours concernant le mois M-1
![15741304_10211609056327469_4054998487848568768_n](https://cloud.githubusercontent.com/assets/23027156/21482258/ac193f30-cb71-11e6-908d-33efab889b03.jpg)

on peut aussi imaginer de barrer les dates non cliquables

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by AlexBillbao** [comment]
Il y a déjà une couleur css gris plus clair pour les jours passés. Il faut juste la mettre encore plus gris clair pour dissuader d'y cliquer, et faire plus ressortir les jours j et à venir. MERCI !!

**Comment by thb** [comment]
Fait

**Comment by ndelavergne** [comment]
Le calendrier ne devait pas être actif seulement sur les trois mois à venir ? j'ai pu déposer une annonce pour août 2017

**Comment by ndelavergne** [comment]
Il est suggéré (dans le groupe FB) 
- Afficher les jours : Lu Ma Me Je Ve Sa Di
- Majuscules sur les mois : Décembre

**Comment by thb** [comment]
Done
