### ISSUE TITLE
rayon de la recherche

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#109]
### Comportement actuel
10km de rayon pour la recherche par défaut, c'est vraiment trop peu... (Maxime)

### Comportement attendu
je ne sais pas. option pour élargir comme sur l'ancien site ?

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by thb** [comment]
Je vais déjà le passer à 25km, ensuite il faudra le mettre en option de recherche avancée je pense

**Comment by thb** [comment]
Passé à 25km
