### ISSUE TITLE
Bouton afficher le téléphone + tracker le téléphone et les messages

### ISSUE THREAD

**Issue by thb** [thb/covoiturage-libre-rails5#117]
### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by ndelavergne** [comment]
j'allais créé l'issue...

**Comment by ndelavergne** [comment]
bon, ça a l'air de marcher point de vue tracking sur analytics, et le bouton marche chez moi pour afficher le numéro de téléphone.
