### ISSUE TITLE
Stats des annonces créées par jour

### ISSUE THREAD

**Issue by thb** [thb/covoiturage-libre-rails5#119]
### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by AlexBillbao** [comment]
Il y a un nouveau lien ?

**Comment by thb** [comment]
https://covoiturage-libre.fr

**Comment by AlexBillbao** [comment]
Saltu Thomas, je voulais dire un nouveau lien pour les stats ! Nico m'avait transmis un lien qui marchait pour l'ancien site mais le lien ne marche plus depuis le transfert ;-D
