### ISSUE TITLE
Mise en place de Google Analytics sur le Wiki

### ISSUE THREAD

**Issue by thb** [thb/covoiturage-libre-rails5#22]

**Comment by Flaburgan** [comment]
Hm, et pourquoi pas Piwik :)

**Comment by thb** [comment]
C'est vrai qu'on souhaite utiliser uniquement des technologies OpenSource mais on ne sait pas bien utiliser Piwik et les stats s'éssouflant un peu, on doit être au plus près de nos données.
Je vais tester Piwik.
Si j'arrive à avoir les même fonctionnalités (création de dimensions personnalisées et tracking d'évènements notamment), on enlèvera GA.
