### ISSUE TITLE
Doublons dans l'autocomplétion

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#31]
Dans le champ "ville" de recherche de trajets, pas mal de doublons.

**Comment by thb** [comment]
Il faut : 
- [ ] voir pour paramétrer nominatim avec geocoder pour limiter la précision des villes
- [ ] voir ce que donne le geocoder de Google utilisé par blabla pour avoir un système similaire

**Comment by thb** [comment]
- [ ] mettre le code postal entre parenthèses après le nom de la ville
- [ ] vérifier le quota dispo pour le nb de geocoding / jour
