### ISSUE TITLE
Compléter le mail de confirmation

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#40]
en particulier en ajoutant la date du trajet.
Et le bouton "ajouter le trajet retour", qui ouvre sur le formulaire avec les villes inversées et pas de date.

**Comment by ndelavergne** [comment]
le modèle est prêt dans mailjet

**Comment by thb** [comment]
Le code HTML généré par Mailjet est bien désastreux, aucun humain ne peut faire cela, on a bien eu raison de passer par Mailjet pour cela :
![image](https://cloud.githubusercontent.com/assets/20539/20505564/3c6f1d78-b04e-11e6-8373-cf3b84470093.png)

**Comment by ndelavergne** [comment]
Bravo pour l'intégration ! Mail bien reçu ! Je m'aperçois qu'il manque juste en bas, une adresse mail (écrivez-nous...). Y a-t-il d'autres modèles de mail à faire ?

**Comment by thb** [comment]
oui, le mail de confirmation de message envoyé et le mail du message reçu

**Comment by ndelavergne** [comment]
Message reçu ? le mail envoyé au conducteur via le formulaire, avec copie à l'expéditeur ? c'est bien ça ?

**Comment by ndelavergne** [comment]
Thomas, tu n'as pas pris le bon template pour le mail de validation de l'annonce : il faut prendre **covolitemplatevalidationseule** et non pas CovoliTemplateValidation (j'avais fait une copie pour garder l'orginal, mais mailjet a des problèmes de gestion des templates, et certaines modifs ont été enregistrées sur l'original - suppression des boutons - mais pas tout - le texte complet est sur covolitemplatevalidationseule.

**Comment by thb** [comment]
Je crois que c'est bon cette fois. J'ai supprimé l'ancien pour qu'il n'y ait pas de confusion. Aussi, si un ticket que tu recettes ne va pas, tu peux enlever le label "ready" et le mettre en "bug", merci :-)
