### ISSUE TITLE
Geomap dynamique pendant qu’on crée son annonce avec récupération des distances et du temps de trajet

### ISSUE THREAD

**Issue by thb** [thb/covoiturage-libre-rails5#48]

**Comment by ndelavergne** [comment]
pour les distances et le temps de trajet, je ne comprends pas. on n'affiche pas ça dans la V2 MVP, non ?

**Comment by thb** [comment]
ah si, on peut, j'ai oublié

**Comment by ndelavergne** [comment]
je ne vois toujours pas l'affichage de distance et temps de trajet

**Comment by thb** [comment]
Affichage de l'annonce : 
![Uploading image.png…]

Au moment de l'édition : 
![image](https://cloud.githubusercontent.com/assets/20539/20566363/14720dce-b195-11e6-9976-a5ef71d863c9.png)
