### ISSUE TITLE
Créer les boutons "Copier le trajet" et "Créer le trajet retour"

### ISSUE THREAD

**Issue by thb** [thb/covoiturage-libre-rails5#49]

**Comment by ndelavergne** [comment]
Pour moi ce n'est pas un enhancement, c'est présent sur la v1

**Comment by thb** [comment]
Ah le terme enhancement c'est par rapport au code actuel de ce projet. Si ce n'est pas un bug, c'est une évolution.

**Comment by ndelavergne** [comment]
Ah ok

**Comment by thb** [comment]
Le fait que ça doive être présent dans cette V2 minimale est indiqué par la Milestone
