### ISSUE TITLE
Prix des étapes

### ISSUE THREAD

**Issue by thb** [thb/covoiturage-libre-rails5#50]

**Comment by ndelavergne** [comment]
j'ai créé l'annonce Paris Lyon avec étape à Auxerre et Mâcon. j'ai bien saisi le prix. Mais ensuite : 
dans la recherche Paris-Auxerre, c'est le prix de l'étape qui doit s'afficher
dans l'annonce, il faut trouver le moyen d'afficher le prix de l'étape

**Comment by ndelavergne** [comment]
Ce n'est pas le prix de l'étape qui s'affiche.

**Comment by thb** [comment]
C'est vrai, mais c'est plus compliqué ça. Si on peut éviter pour la V2 mvp ça m'arrange, d'autant que ce n'est pas dans la v1 il me semble... si ?

**Comment by ndelavergne** [comment]
Je suis d'accord avec toi, je ne crois pas que ce soit sur la v1, mais là je ne peux pas trouver de trajet avec étape(s) pour tester. Il suffirait d'afficher un petit message, quand il y a des étapes : "pour le prix d'une partie du trajet, arrangez-vous directement avec le conducteur" ou quelque chose comme ça. Sinon, on laisse juste comme ça, comme c'est sur le site actuel.
