### ISSUE TITLE
Pouvoir créer, supprimer des étapes

### ISSUE THREAD

**Issue by thb** [thb/covoiturage-libre-rails5#51]

**Comment by ndelavergne** [comment]
Dans une annonce normale, ou une new_from_copy, ça marche bien, l'ajout et la suppression d'étapes. Mais... il semble qu'il y a encore un petit bug.
Dans une annonce retour, je peux modifier le champ ville d'une étape, ça marche, mais si je supprime une étape, et que j'en remets une, alors elle devient le point de départ. 
http://screencast.com/t/swRvD5DN
Et le point de départ n'est plus pris en compte si je supprime toutes les étapes.
http://screencast.com/t/zIpoWGwiCn

**Comment by ndelavergne** [comment]
Le problème n'est pas réglé, quand j'ajoute une étape dans le formulaire de trajet retour, la ville étape ajoutée prend la place de la ville de départ
http://screencast.com/t/Nlcf6y3OIbY

**Comment by ndelavergne** [comment]
Le problème n'est pas réglé, quand j'ajoute une étape dans le formulaire de trajet retour, la ville étape ajoutée prend la place de la ville de départ
http://screencast.com/t/Nlcf6y3OIbY
