### ISSUE TITLE
limiter l'affichage des minutes de 5 en 5

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#54]
### Comportement actuel
dans le menu déroulant minutes, on a les 60

### Comportement attendu
Seulement de 5 en 5 [0, 5, 10, 15, 20, 25, 30...]

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by thb** [comment]
J'ai changé de façon de faire, en utilisant le HTML5, est-ce que ça va ou je remets le truc classique ?

![image](https://cloud.githubusercontent.com/assets/20539/20285239/0ee02830-aac1-11e6-90a5-afba206126b1.png)

**Comment by thb** [comment]
Si ça ne va pas je mets comme cela : 
![image](https://cloud.githubusercontent.com/assets/20539/20285402/f84f7250-aac1-11e6-8d7c-53b61326c7b9.png)
