### ISSUE TITLE
affichage des boutons "copier" et "retour"

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#55]
### Comportement actuel
les boutons s'affichent systématiquement en bas de l'annonce

### Comportement attendu
copier le trajet - créer le trajet retour : ça ne doit pas s'afficher systématiquement, mais seulement pour la personne qui a créé l'annonce, c'est à dire lorsqu'elle a soumis son annonce, et lorsqu'elle l'a validée. Pour les autres internautes, ça ne doit pas s'afficher (c'est pour ça que c'est un écran différent de l'annonce dans la v1, non ?). je ne sais pas si c'est faisable.

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by ndelavergne** [comment]
ça me paraît compliqué de ne pas les afficher systématiquement (selon quelles variables elles ne s'afficheraient pas ? à l'avenir, quand il y aura des comptes, ces boutons n'apparaîtront que pour l'utilisateur connecté dont c'est l'annonce, et ce sera réglé). Donc là

**Comment by thb** [comment]
Donc on les enlève de la page du trajet mais ils sont dans le mail de gestion et dans toutes les pages de confirmation de l'annonce. Ok pour toi ?
