### ISSUE TITLE
ne peut pas être dans le passé

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#56]
### Comportement actuel
quand on fait une recherche avec une date passée, on a un message "ne peut pas être dans le passé" sous le champ date

### Comportement attendu
remplacer par "Cherchez une date future"

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by ndelavergne** [comment]
Est-ce qu'on peut laisser le champ date sur la même horizontale que les champs villes de départ d'arriver et que le bouton ? en mettant le texte "cherchez une date future" en dessous.

**Comment by thb** [comment]
Il y a un pb d'alignement des champs input de ce formulaire lorsqu'il y a des messages d'erreurs en effet. Tout ce qui est intégration n'est pas ma spécialité, il faut que je regarde. Cependant j'aimerais bien créer un ticket spécifique pour cela, et qu'il ne soit pas dans la milestone MVP V2 si possible. Si ça perturbe trop les utilisateurs il faut le laisser en MVP v2

**Comment by ndelavergne** [comment]
OK, on peut le sortir de MVP v2, et régler ça plus tard. Ce n'est pas bloquant.

**Comment by thb** [comment]
ok
