### ISSUE TITLE
Mail d'administration

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#58]
### Comportement actuel
Le mail d'administration dont on demande le renvoi, est identique au mail de validation

### Comportement attendu
le mail d'administration ne doit pas comporter le bouton "valider l'annonce" car l'annonce a déjà été validée.

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by thb** [comment]
je le fais dès que tu as fait les modifs sur le template avec le mail de contact en bas de page + rapetisser les liens réseaux sociaux car je ne peux pas intégrer des petites modifs dans un template, c'est tout ou rien

**Comment by ndelavergne** [comment]
c'est bon pour moi, ce mail là.
