### ISSUE TITLE
affichage de "c'est votre annonce" + boutons copier/retour

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#59]
### Comportement actuel
cette phrase et ce lien sont affichés au dessus de la boîte de droite (conducteur)

### Comportement attendu
créer une boîte supplémentaire sous le bloc "envoyer un message", et y mettre le texte suivant : 

C'est votre annonce et vous souhaitez la modifier/supprimer ? Utilisez les liens présents dans le courriel de confirmation que vous avez reçu lors de la création de l'annonce.
Vous avez perdu le courriel de confirmation ? Cliquez ici pour le recevoir à nouveau.
Bouton "créer le retour"
Bouton "dupliquer l'annonce"

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by ndelavergne** [comment]
cf issue #55 pour les boutons copier et retour.

**Comment by ndelavergne** [comment]
cf issue #77 pour les boutons copier et retour : soit il y a un moyen de contrôler l'identité de celui qui duplique depuis le site (pop up lui demandant son mail, par ex.), soit ces fonctions ne doivent être accessibles que dans les mails de validation et d'administration (celui qui peut être renvoyé à la demande), et il faut compléter le mail de validation en ajoutant, outre "créer le retour", un 5e bouton "dupliquer l'annonce".

**Comment by thb** [comment]
Fait, en supprimant les butons copier et retour, car ils sont dans le mail de gestion et en raccourcis rapides dans les écrans de confirmation, validation, etc.

**Comment by ndelavergne** [comment]
ok
