### ISSUE TITLE
Faire en sorte que le bouton "publier une annonce" soit visible en responsive

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#67]
### Comportement actuel
le bouton n'est accessible en responsive qu'en déroulant le menu sandwich

### Comportement attendu
le bouton doit être visible au-dessus des champs de recherche sans qu'on ait à cliquer. 

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by thb** [comment]
Je le mets en dessus du champ recherche car je crois que c'est mieux ainsi
