### ISSUE TITLE
Améliorations formulaire d'ajout d'annonce / suggestions Maxime Baviere

### ISSUE THREAD

**Issue by thb** [thb/covoiturage-libre-rails5#69]
Certains champs du formulaire de dépose d'annonce (présents dans la V1) sont utiles :

- [x] bouton déposer une annonce: "le site ne prend aucune commission / association loi 1901"
- [x] commentaire : "important, les annonces avec commentaires sont plus efficaces : détails sur votre parcours, sur le lieu précis du départ, sur vos attentes, si vous acceptez les animaux de compagnie, etc."
- [x] téléphone : "Votre numéro de téléphone sera affiché tel quel. Si vous ne souhaitez pas laisser votre numéro sur le site, ne remplissez pas ce champ"
- [x] email : "Obligatoire et valide. Un message de confirmation vous y sera envoyé."
Pour éviter de surcharger la page en texte, peut-être sous forme de boutons "?" ou "plus d'info" qui ouvrent une pop-up ou autre...
autres améliorations :
- [x] agrandir la taille des flèches qui permettent d'augmenter/diminuer le nombre de place/ prix
- [x] Rajouter "les champs précédés d'un astérisque sont obligatoires" , dans la fenêtre de dépôt d'annonce et de prise de contact avec le conducteur

**Comment by ndelavergne** [comment]
ajouter le texte suivant à côté du bouton "ajouter des étapes"
(prix à partir de la ville de départ)
cf http://screencast.com/t/Kb3qFQt4Ooj

**Comment by ndelavergne** [comment]
je valide mon annonce, mais j'ai un message d'erreur, cependant aucun champ n'apparaît en erreur
http://screencast.com/t/28napdCX
je ne peux donc pas tester la suite

**Comment by thb** [comment]
Oups ! j'ai oublié qu'il ne fallait un prix sur les points du trajet que pour les étapes intermédiaires...

**Comment by ndelavergne** [comment]
Pour moi c'est pas ready, voir mes deux commentaires, sur la ligne à ajouter à côté du bouton "ajouter des étapes" et sur le fait que je ne parviens pas à enregistrer mon annonce. et idem sur mon téléphone.

**Comment by thb** [comment]
J'ai déjà mis à jour Nicolas
