### ISSUE TITLE
mettre une heure par défaut

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#70]
### Comportement actuel
les champs heure et minutes sont vides, le menu déroulant file vers le bas de la page.

### Comportement attendu
Petite amélioration ergonomique: mettre l'heure par défaut sur 12h et les minutes par défaut sur 00. 12h est central et évite de descendre dans la liste déroulante la plupart du temps, 00 est le plus probable et donc ça économise deux clics.
Dans le même ordre d'idée, ne mettre que 4 valeurs pour l'heure : 00, 15, 30 et 45.

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by thb** [comment]
Je trouve que ça devrait être hors MVP cette demande, ou il faut d'avantage de demandes de la communauté pour le faire car par exemple, sur le site meetup.com, la liste des heures et minutes est encore plus longue et ça n'empêche pas le site de fonctionner très bien...

**Comment by ndelavergne** [comment]
C'est compliqué à faire ? On peut poser la question dans le groupe. Je n'ai rien contre le fait de le sortir de la MVP, c'est juste que ça me semble constituer un gain important de clics : de façon générale, du coup, pas de double clic pour choisir 00 en minutes, et pour les heures, deux clics suffisent, pas besoin de dérouler les heures pour arriver à 18h.

**Comment by ndelavergne** [comment]
Sur le site actuel, c'est le cas : heure par défaut dans les cases est 12h00.

**Comment by thb** [comment]
C'est fait.

**Comment by ndelavergne** [comment]
perfect
