### ISSUE TITLE
Page d'erreur 404 personnalisée

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#74]
### Comportement attendu
créer une page d'erreur 404 personnalisée
http://screencast.com/t/wDpJVbQpPp

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by thb** [comment]
manque juste les images

**Comment by ndelavergne** [comment]
Les images sont dans le slack. les revoici
![erreur-404](https://cloud.githubusercontent.com/assets/23027156/20759626/b78643f8-b71d-11e6-9231-ff8d57e1088a.png)
![erreur-500](https://cloud.githubusercontent.com/assets/23027156/20759628/ba0506e6-b71d-11e6-9886-585a7b790f2f.png)
![annonce-supprime-et-et-autre](https://cloud.githubusercontent.com/assets/23027156/20759634/bd1d5450-b71d-11e6-999e-503db89fb8c6.png)

**Comment by ndelavergne** [comment]
je tombe bien sur l'erreur 500 mais je ne sais pas comment générer la 404
