### ISSUE TITLE
duplication ou annonce retour : affiche des données personnelles

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#77]
### Comportement actuel
je clique sur création du retour d'une annonce que je n'ai pas crée, ça affiche dans les cases correspondantes les numéros de tél et mail de celui qui a déposé l'adresse.
ex : https://covoli.scalingo.io/trajets/mmgQyED37ua23Nnywc6HHWuR/new_from_copy
http://screencast.com/t/RYyUQNOH

### Comportement attendu
là je ne sais pas comment faire, on ne peut pas identifier celui qui clique. 
donc soit il faut vider ces deux champs (mail et numéro de tél)
soit une étape intermédiaire qui vérifie l'identité de celui qui veut dupliquer (par ex. un pop up qui lui demande son email) et puis si ça matche, on affiche la page de duplication de l'annonce
il y a peut-être une autre solution.
dans l'état, on ne peut pas laisser comme ça accessibles les mails et tél du conducteur qui a posé l'annonce

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by thb** [comment]
Nicolas, ces liens ne sont plus sur la page de l'annonce, ils sont maintenant uniquement sur les pages de confirmation que seul voit le propriétaire de l'anonce

**Comment by ndelavergne** [comment]
ok
