### ISSUE TITLE
Modification du calendrier

### ISSUE THREAD

**Issue by Louiseblaaa** [thb/covoiturage-libre-rails5#79]
### Comportement actuel
Quand le calendrier s'affiche, toutes les dates sont accessibles, mêmes celles passées. Quand on lance la recherche, la page se recharge et un message d'erreur s'affiche "Cherchez une date future".

### Comportement attendu
Désactiver les dates antérieures afin d'éviter l'affichage de la page avec le message d'erreur puis recommencer la recherche => gain de temps.

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by Louiseblaaa** [comment]
Super ^_^

**Comment by ndelavergne** [comment]
parfait
