### ISSUE TITLE
le bouton copier le trajet ne fonctionne pas sur la page annonce confirmée

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#90]
### Comportement actuel
le bouton renvoie vers cette page d'erreur
http://screencast.com/t/JiPUI0IF

### Comportement attendu
le formulaire avec les mêmes villes et sans date

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by ndelavergne** [comment]
et le bouton trajet retour ne marche pas non plus

**Comment by thb** [comment]
heu... tu es sûr que l'annonce était confirmée et pas supprimée ? je demande un retest pour être sûr ^^

**Comment by ndelavergne** [comment]
non, effectivement, l'annonce n'était pas confirmée, c'est sur la page "Merci, votre annonce a bien été enregistrée", que les boutons copier et retour ne marchent pas
http://screencast.com/t/9kPDyRnB4k
effectivement à ce stade, le trajet n'est pas encore validé. mais du coup les boutons ne servent à rien, car sur cette page "Merci....", jamais le trajet n'est validé (on n'a pas encore cliqué sur le mail). 
même si je valide l'annonce par ailleurs dans un autre onglet, ça ne marche pas.

**le fait que l'annonce soit validée ne doit pas ici être une condition pour pouvoir dupliquer ou créer le trajet retour.** c'est pas juste ça le problème ?

**Comment by thb** [comment]
Oui tout à fait, bien vu

Le mer. 30 nov. 2016 à 00:00, ndelavergne <notifications@github.com> a
écrit :

**Comment by thb** [comment]
Bizarre je checke

**Comment by thb** [comment]
Ok il y avait bien un bug. En fait les liens sur les raccourcis rapides étaient avec le "confirmation_token" et non avec le "edition_token".

**Comment by ndelavergne** [comment]
Réglé
