### ISSUE TITLE
prix d'une étape obligatoire

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#91]
### Comportement actuel
si je ne saisis pas de prix, j'ai un message d'erreur
http://screencast.com/t/FSHL5E0Mkx1

### Comportement attendu
pourtant le champ prix n'a pas d'étoile indiquant l'obligation de le remplir
soit il n'est pas obligatoire, soit il l'est et doit avoir un astérisque

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by thb** [comment]
Oui, mais en fait le pb est que le prix n'a pas de label sur lequel placer une asterisque. Ou alors je le mets dans le placeholder. Je vais faire un test.

**Comment by ndelavergne** [comment]
Solution intelligente !
