### ISSUE TITLE
On peut modifier une annonce qui n'est pas la sienne

### ISSUE THREAD

**Issue by BSibille** [thb/covoiturage-libre-rails5#94]
### Comportement actuel
Quand je visualise une annonce de trajet, tout en bas de la page (à gauche en dessous du cadre "C'est votre annonce et vous souhaitez la modifier") il y a un lien "modifier" qui me permet, quand je clique dessus, de modifier l'annonce bien que ce ne soit pas l'annonce.

ex. : https://covoli.scalingo.io/trajets/1KRCJt1qt2am9ztrbKs4AHpc

### Comportement attendu
Le lien "modifier ne devrait pas être visible.

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by ndelavergne** [comment]
Le lien "modifier" ne devrait pas apparaître du tout
