### ISSUE TITLE
Sous quelle licence est le code ?

### ISSUE THREAD

**Issue by jibe-b** [thb/covoiturage-libre-rails5#95]
Salut à tous !

C'est super que le code de covoiturage-libre soit sur github ! Il n'y a pour le moment pas de fichier de licence. Laquelle s'applique ? Je fais le lien avec une petite asso qui pourrait se baser sur le code de covoiturage-libre pour développer ses user cases (et si ça avance bien, on fera des pull requests).

Bien à vous,

**Comment by flexbox** [comment]
Hello there
Hmmmm on ne s'est pas encore posé la question, mais pour trouver il y a des morceaux de réponse ici 
http://choosealicense.com/

**Comment by thb** [comment]
on va y réfléchir avec le président de l'asso, Bastien Sibille, spécialiste du sujet (il a fait une thèse sur les licences du code informatique au Canada et connait Richard Stallman, excusez du peu...)

**Comment by flexbox** [comment]
Tu veux dire le mec à droite ? 
![Richard Stallman & flexbox](https://farm8.staticflickr.com/7415/16419176601_e244bf4c83.jpg)

**Comment by thb** [comment]
Nooooooonnnnn !!!!! Génial !

**Comment by Karmak23** [comment]
J'ai aussi étudié les licenses libres / open source / etc, et si j'ai une suggestion, c'est la GNU Affero GPL v3.
licence de logiciel libre, avec des vertus sociales dedans.
La variante Affero s'applique aux logiciels qui tournent sur les serveurs web, pour permettre aux utilisateurs d'un SERVICE web, d'en obtenir les sources.
Une licence de type GPL v2/v3 "classique" ne couvre que les logiciels exécutables sur la machine locale, elle ne serait donc d'aucune utilité pour un service web.

Je suis tellement content de voir la congruence de ce projet, que le code source apparaisse enfin, c'est totalement consistant avec le côté « bien commun ». Ça fait longtemps que j'attendais ça. Vous allez probablement être le premier "bien commun d'envergure" (= le covoiturage en tant que bien commun), ça va ouvrir la porte — au moins conceptuellement — à se réapproprier doucement tous les autres.

Longue vie au projet, et même si ça un jour ça foire, ça évolue, ça change, peu importe. Ce que vous avez fait ici est indéniablement un gigantesque pas dans le bon sens.
MERCI.

**Comment by jibe-b** [comment]
MERCI ! tout comme @Karmak23 c'est la principale chose qui mérite de vous être dite !
Et pour vous tenir au courant, la petite association que je citais quand je participais au lobbying pour la libération du code, cette asso bossera début mars sur leur projet covoiturage pour assos, et j'espère bien faire une preuve de principe d'ici là que covoiturage-libre est facilement étendable (genre un petit module backend et un minimum d'extension de l'interface) afin de séparer le dev de fonctionnalités diffbrentes mais d'amener quelques dev (amateurs, certes) dans la communauté covoiturage-libre. Voilou.

**Comment by Flaburgan** [comment]
Le choix s'est donc porté sur la GPL et non pas la AGPL ?
