### ISSUE TITLE
Résoudre les problèmes liés au partage sur facebook/méta og

### ISSUE THREAD

**Issue by ndelavergne** [thb/covoiturage-libre-rails5#99]
### Comportement actuel
Le débogueur de FB indique plusieurs problèmes
http://screencast.com/t/dfPxKmaVBJE7

Parser Mismatched Metadata
The parser's result for this metadata did not match the input metadata. Likely, this was caused by the data being ordered in an unexpected way, multiple values being given for a property only expecting a single value, or property values for a given property being mismatched. Here are the input properties that were not seen in the parsed result: 'og:description, og:site_name, og:image:url'

Propriété déduite
The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.

### Comportement attendu

1. Peut-être c'est juste parce que property doit être avant content ?

2. Pour l'image, il faut ajouter ceci car on est en https
<meta property="og:image:secure_url" content="https://covoiturage-libre.fr/covoiturage-libre-RS-noel.png" />

### Étapes pour reproduire le problème

[] Développement
[] Production

**Comment by thb** [comment]
Si tu regardes le code source de la page, tu vois que je l'ai bien mis, je ne comprends pas.
Je t'invite sur l'app Facebook.
Pour info, c'est cette app qui gère l'authentification facebook. (Facebook Connect)

**Comment by ndelavergne** [comment]
Moi je croyais que l'app gérait les relations avec la page facebook (le nombre de j'aime, etc.)
